source 'https://rubygems.org'
gem 'selenium-webdriver'
gem 'rspec', :require => 'spec'
gem 'rake'
gem 'activerecord', '~> 6.0.2'
gem 'capybara', '~> 3.11.1'
gem 'thor'
<% require "lopata/version" %>
gem 'lopata', '<%= Lopata::Version::STRING %>'
