source 'https://rubygems.org'
gem 'selenium-webdriver'
gem 'rspec', :require => 'spec'
gem 'rake'
gem 'activerecord', '~> 4.2.0'
gem 'capybara', '~> 2.2.1' # fix capybara version to avoid capybara-angular deprication varnings.
gem 'thor'
