#!/usr/bin/env ruby
require 'bundler/setup'
require 'lopata/runner'

# use default command with arguments if given command is unknown.
argv = ARGV.dup
unless Lopata::Runner.all_commands.keys.map(&:to_s).include? argv.first
  argv.unshift 'test'
end

Lopata::Runner.start argv
